name: HideAndCustomPlugins
main: at.mcnetwork.lausi.HideAndCustomPlugins
softdepend: [ProtocolLib]
version: 1.8.1
author: LauseggerDevelopment
website: http://dev.bukkit.org/bukkit-plugins/hideandcustomplugins/
commands:
  hcp:
    usage: /hcp
    description: Information about the plugin.
    permission: hideandcustomplugins.info

permissions:
  hideandcustomplugins.*:
    description: Only OP
    children:
      hideandcustomplugins.info: true
      hideandcustomplugins.bypass: true
      hideandcustomplugins.reload: true
      hideandcustomplugins.add: true
      hideandcustomplugins.remove: true
      hideandcustomplugins.blacklist: true
      hideandcustomplugins.whitelist: true
      hideandcustomplugins.plugin.*: true
    default: op
  hideandcustomplugins.reload:
    description: Reload of the config.yml.
  hideandcustomplugins.bypass:
    description: Bypasses the plugin.
  hideandcustomplugins.info:
    description: Shows Information about the plugin.
  hideandcustomplugins.add:
    description: Add a command to the blacklist.
  hideandcustomplugins.remove:
    description: Remove a command from the blacklist.
  hideandcustomplugins.blacklist:
    description: Shows a list with the blocked commands.
  hideandcustomplugins.whitelist:
    description: Manage the command whitelist
  hideandcustomplugins.plugin.*:
    description: Allows using a blocked plugin
